<script>

var EPBOUWERConfig = {
	debug: <?php if( defined( 'WP_DEBUG' ) && WP_DEBUG ) echo 'true'; else echo 'false'; ?>,
	enabledTemplates: '<?php echo $enabled_templates; ?>',
	help: <?php echo json_encode( $help_button ); ?>,
	homeUrl:  '<?php echo home_url(); ?>',
	isRtl:  <?php if(is_rtl()) echo 'true'; else echo 'false'; ?>,
	lite: <?php if(EP_BOUWER_LITE === true) echo 'true'; else echo 'false'; ?>,
	newUser: <?php if ( EPBOUWERModel::is_new_user() ) echo 'true'; else echo 'false'; ?>,
	postId: <?php echo $post_id; ?>,
	postType: '<?php echo get_post_type(); ?>',
	simpleUi: <?php if(!current_user_can(EPBOUWERModel::get_editing_capability())) echo 'true'; else echo 'false'; ?>,
	upgradeUrl: '<?php if(EP_BOUWER_LITE === true) $campaign = 'upgrade-button'; else $campaign = 'buy-button'; echo EPBOUWERModel::get_upgrade_url( array( 'utm_source' => 'external', 'utm_medium' => 'builder', 'utm_campaign' => $campaign ) ); ?>'
};

var EPBOUWERStrings = {
	actionsLightboxTitle: '<?php esc_attr_e('What would you like to do?', 'ep-bouwer'); ?>',
	cancel: '<?php esc_attr_e('Cancel', 'ep-bouwer'); ?>',
	changeTemplate: '<?php esc_attr_e('Change Template', 'ep-bouwer'); ?>',
	changeTemplateMessage: '<?php esc_attr_e('Warning! Changing the template will replace your existing layout. Do you really want to do this?', 'ep-bouwer'); ?>',
	column: '<?php esc_attr_e('Column', 'ep-bouwer') ?>',
	columnSettings: '<?php esc_attr_e('Column Settings', 'ep-bouwer') ?>',
	contentSliderSelectLayout:  '<?php esc_attr_e('Please select either a background layout or content layout before submitting.', 'ep-bouwer'); ?>',
	deleteAccount: '<?php esc_attr_e('Remove Account', 'ep-bouwer'); ?>',
	deleteAccountWarning: '<?php esc_attr_e('Are you sure you want to remove this account? Other modules that are connected to it will be affected.', 'ep-bouwer'); ?>',
	deleteFieldMessage: '<?php esc_attr_e('Do you really want to delete this item?', 'ep-bouwer'); ?>',
	deleteModuleMessage: '<?php esc_attr_e('Do you really want to delete this module? All content data will be permanently deleted.', 'ep-bouwer') ?>',
	deleteRowMessage: '<?php esc_attr_e('Do you really want to delete this row? All content data will be permanently deleted.', 'ep-bouwer') ?>',
	deleteTemplate: '<?php esc_attr_e('Do you really want to delete this template?', 'ep-bouwer'); ?>',
	discard: '<?php esc_attr_e('Discard Changes', 'ep-bouwer'); ?>',
	discardMessage: '<?php esc_attr_e('Do you really want to discard these changes? All of your changes that are not published will be lost.', 'ep-bouwer'); ?>',
	done: '<?php esc_attr_e('Done', 'ep-bouwer'); ?>',
	draft: '<?php esc_attr_e('Save Draft', 'ep-bouwer'); ?>',
	duplicate: '<?php _ex( 'Duplicate', 'Duplicate page/post action label.', 'ep-bouwer' ); ?>',
	duplicatePage: '<?php esc_attr_e('Duplicate This Page', 'ep-bouwer'); ?>',
	duplicateTemplate: '<?php esc_attr_e('Duplicate This Template', 'ep-bouwer'); ?>',
	editGlobalSettings: '<?php esc_attr_e('Edit Global Settings', 'ep-bouwer'); ?>',
	emptyMessage: '<?php esc_attr_e('Drop a row layout or module to get started!', 'ep-bouwer') ?>',
	errorMessage: '<?php esc_attr_e('Epic Bouwer caught the following JavaScript error. If Epic Bouwer is not functioning as expected the cause is most likely this error. Please help us by disabling all plugins and testing Epic Bouwer while reactivating each to determine if the issue is related to a third party plugin.', 'ep-bouwer') ?>',
	fullSize: '<?php esc_attr_e('Full Size', 'ep-bouwer'); ?>',
	getHelp: '<?php esc_attr_e('Get Help', 'ep-bouwer'); ?>',
	gettingStartedVideo: '<?php esc_attr_e('Getting Started Video', 'ep-bouwer'); ?>',
	globalErrorMessage: '<?php _e('"{message}" on line {line} of {file}.', 'ep-bouwer') ?>',
	insert: '<?php esc_attr_e('Insert', 'ep-bouwer'); ?>',
	large: '<?php esc_attr_e('Large', 'ep-bouwer'); ?>',
	manageTemplates: '<?php esc_attr_e('Manage Templates', 'ep-bouwer'); ?>',
	medium: '<?php esc_attr_e('Medium', 'ep-bouwer'); ?>',
	module: '<?php esc_attr_e('Module', 'ep-bouwer') ?>',
	move: '<?php esc_attr_e('Move', 'ep-bouwer'); ?>',
	newColumn: '<?php esc_attr_e('New Column', 'ep-bouwer') ?>',
	newRow: '<?php esc_attr_e('New Row', 'ep-bouwer') ?>',
	noResultsFound: '<?php esc_attr_e('No results found.', 'ep-bouwer') ?>',
	noThanks: '<?php esc_attr_e('No Thanks', 'ep-bouwer'); ?>',
	ok: '<?php esc_attr_e( 'OK', 'ep-bouwer' ); ?>',
	photoPage: '<?php esc_attr_e('Photo Page', 'ep-bouwer'); ?>',
	photoSelected: '<?php esc_attr_e('Photo Selected', 'ep-bouwer'); ?>',
	photosSelected: '<?php esc_attr_e('Photos Selected', 'ep-bouwer'); ?>',
	pleaseWait: '<?php esc_attr_e('Please Wait...', 'ep-bouwer'); ?>',
	publish: '<?php esc_attr_e('Publish Changes', 'ep-bouwer'); ?>',
	remove: '<?php esc_attr_e('Remove', 'ep-bouwer'); ?>',
	row: '<?php esc_attr_e('Row', 'ep-bouwer') ?>',
	rowSettings: '<?php esc_attr_e('Row Settings', 'ep-bouwer') ?>',
	saveCoreTemplate: '<?php esc_attr_e('Save Core Template', 'ep-bouwer'); ?>',
	saveTemplate: '<?php esc_attr_e('Save Template', 'ep-bouwer'); ?>',
	selectPhoto: '<?php esc_attr_e('Select Photo', 'ep-bouwer'); ?>',
	selectPhotos: '<?php esc_attr_e('Select Photos', 'ep-bouwer'); ?>',
	selectVideo: '<?php esc_attr_e('Select Video', 'ep-bouwer'); ?>',
	settings: '<?php _ex( '%s Settings', '%s stands for module name.', 'ep-bouwer' ); ?>',
	subscriptionModuleAccountError: '<?php esc_attr_e('Please select an account before saving.', 'ep-bouwer'); ?>',
	subscriptionModuleConnectError: '<?php esc_attr_e('Please connect an account before saving.', 'ep-bouwer'); ?>',
	subscriptionModuleListError: '<?php esc_attr_e('Please select a list before saving.', 'ep-bouwer'); ?>',
	takeHelpTour: '<?php esc_attr_e('Take a Tour', 'ep-bouwer'); ?>',
	templateAppend: '<?php esc_attr_e('Append New Layout', 'ep-bouwer'); ?>',
	templateReplace: '<?php esc_attr_e('Replace Existing Layout', 'ep-bouwer'); ?>',
	templateSaved: '<?php esc_attr_e('Template Saved!', 'ep-bouwer'); ?>',
	thumbnail: '<?php esc_attr_e('Thumbnail', 'ep-bouwer'); ?>',
	tourNext: '<?php esc_attr_e('Next', 'ep-bouwer'); ?>',
	tourEnd: '<?php esc_attr_e('Get Started', 'ep-bouwer'); ?>',
	tourTemplatesTitle: '<?php esc_attr_e('Choose a Template', 'ep-bouwer'); ?>',
	tourTemplates: '<?php esc_attr_e('Get started by choosing a layout template to customize, or build a page from scratch by selecting the blank layout template.', 'ep-bouwer'); ?>',
	tourAddRowsTitle: '<?php esc_attr_e('Add Rows', 'ep-bouwer'); ?>',
	tourAddRows: '<?php esc_attr_e('Add multi-column rows, adjust spacing, add backgrounds and more by dragging and dropping row layouts onto the page.', 'ep-bouwer'); ?>',
	tourAddContentTitle: '<?php esc_attr_e('Add Content', 'ep-bouwer'); ?>',
	tourAddContent: '<?php esc_attr_e('Add new content by dragging and dropping modules or widgets into your row layouts or to create a new row layout.', 'ep-bouwer'); ?>',
	tourEditContentTitle: '<?php esc_attr_e('Edit Content', 'ep-bouwer'); ?>',
	tourEditContent: '<?php esc_attr_e('Move your mouse over rows, columns or modules to edit and interact with them.', 'ep-bouwer'); ?>',
	tourEditContent2: '<?php esc_attr_e('Use the action buttons to perform actions such as moving, editing, duplicating or deleting rows, columns and modules.', 'ep-bouwer'); ?>',
	tourAddContentButtonTitle: '<?php esc_attr_e('Add More Content', 'ep-bouwer'); ?>',
	tourAddContentButton: '<?php esc_attr_e('Use the Add Content button to open the content panel and add new row layouts, modules or widgets.', 'ep-bouwer'); ?>',
	tourTemplatesButtonTitle: '<?php esc_attr_e('Change Templates', 'ep-bouwer'); ?>',
	tourTemplatesButton: '<?php esc_attr_e('Use the Templates button to pick a new template or append one to your layout. Appending will insert a new template at the end of your existing page content.', 'ep-bouwer'); ?>',
	tourToolsButtonTitle: '<?php esc_attr_e('Helpful Tools', 'ep-bouwer'); ?>',
	tourToolsButton: '<?php esc_attr_e('The Tools button lets you duplicate a page, save a template or edit the global settings.', 'ep-bouwer'); ?>',
	tourDoneButtonTitle: '<?php esc_attr_e('Publish Your Changes', 'ep-bouwer'); ?>',
	tourDoneButton: '<?php esc_attr_e("Once you're finished, click the Done button to publish your changes, save a draft or revert back to the last published state.", 'ep-bouwer'); ?>',
	tourFinishedTitle: '<?php esc_attr_e("Let's Get Building!", 'ep-bouwer'); ?>',
	tourFinished: '<?php esc_attr_e("Now that you know the basics, you're ready to start building! If at any time you need help, click the help icon in the upper right corner to access the help menu. Happy building!", 'ep-bouwer'); ?>',
	unloadWarning: '<?php esc_attr_e('The settings you are currently editing will not be saved if you navigate away from this page.', 'ep-bouwer'); ?>',
	viewKnowledgeBase: '<?php esc_attr_e('View the Knowledge Base', 'ep-bouwer'); ?>',
	visitForums: '<?php esc_attr_e('Visit the Forums', 'ep-bouwer'); ?>',
	watchHelpVideo: '<?php esc_attr_e('Watch the Video', 'ep-bouwer'); ?>',
	welcomeMessage: '<?php esc_attr_e('Welcome! It looks like this might be your first time using the builder. Would you like to take a tour?', 'ep-bouwer'); ?>',
	yesPlease: '<?php esc_attr_e('Yes Please!', 'ep-bouwer'); ?>'
};

</script>