<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="//how2behealthy.nl/wp-content/plugins/wordpress-seo/css/main-sitemap.xsl"?>
<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd http://www.google.com/schemas/sitemap-image/1.1 http://www.google.com/schemas/sitemap-image/1.1/sitemap-image.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
	<url>
		<loc>https://how2behealthy.nl/type/gallery/</loc>
		<lastmod>2018-02-15T14:31:20+00:00</lastmod>
	</url>
	<url>
		<loc>https://how2behealthy.nl/type/image/</loc>
		<lastmod>2018-02-15T13:56:26+00:00</lastmod>
	</url>
	<url>
		<loc>https://how2behealthy.nl/type/quote/</loc>
		<lastmod>2018-02-15T14:20:31+00:00</lastmod>
	</url>
</urlset>
<!-- XML Sitemap generated by Yoast SEO -->